apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: techdocs-example
  description: Example TechDocs repository
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: production
  owner: user:kishore.ravi # Replace with your Backstage user or group